USE [master]
GO
/****** Object:  Database [PeopleSearch]    Script Date: 9/23/2016 10:59:34 AM ******/
CREATE DATABASE [PeopleSearch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PeopleSearch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PeopleSearch.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PeopleSearch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PeopleSearch_log.ldf' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PeopleSearch] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeopleSearch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PeopleSearch] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PeopleSearch] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PeopleSearch] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PeopleSearch] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PeopleSearch] SET ARITHABORT OFF 
GO
ALTER DATABASE [PeopleSearch] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PeopleSearch] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PeopleSearch] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PeopleSearch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PeopleSearch] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PeopleSearch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PeopleSearch] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PeopleSearch] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PeopleSearch] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PeopleSearch] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PeopleSearch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PeopleSearch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PeopleSearch] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PeopleSearch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PeopleSearch] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PeopleSearch] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PeopleSearch] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PeopleSearch] SET RECOVERY FULL 
GO
ALTER DATABASE [PeopleSearch] SET  MULTI_USER 
GO
ALTER DATABASE [PeopleSearch] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PeopleSearch] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PeopleSearch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PeopleSearch] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [PeopleSearch] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PeopleSearch', N'ON'
GO
USE [PeopleSearch]
GO
/****** Object:  Table [dbo].[PersonDetails]    Script Date: 9/23/2016 10:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PersonDetails](
	[PersonId] [int] NOT NULL,
	[FirstName] [varchar](max) NULL,
	[LastName] [varchar](max) NULL,
	[Age] [int] NULL,
	[Address] [varchar](max) NULL,
	[Interests] [varchar](max) NULL,
 CONSTRAINT [PK_PersonDetails] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Picture]    Script Date: 9/23/2016 10:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Picture](
	[PersonId] [int] NOT NULL,
	[Picture] [varchar](max) NULL,
 CONSTRAINT [PK_Picture] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[PersonDetails]  WITH CHECK ADD  CONSTRAINT [FK_PersonDetails_PersonDetails] FOREIGN KEY([PersonId])
REFERENCES [dbo].[PersonDetails] ([PersonId])
GO
ALTER TABLE [dbo].[PersonDetails] CHECK CONSTRAINT [FK_PersonDetails_PersonDetails]
GO
USE [master]
GO
ALTER DATABASE [PeopleSearch] SET  READ_WRITE 
GO
